version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd authorization-service
      - mvn clean package
      - echo Building the docker image
      - docker build -t authorization-service .
      - docker tag authorization-service 860061945305.dkr.ecr.ap-south-1.amazonaws.com/bang-auth-repo-ecr-2:Auth
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 860061945305.dkr.ecr.ap-south-1.amazonaws.com/bang-auth-repo-ecr-2:Auth
      - echo Writing definition files
      - printf '[{"name":"bang-Auth-container","imageUri":"%s"}]' 860061945305.dkr.ecr.ap-south-1.amazonaws.com/bang-auth-repo-ecr-2:Auth > taskdefinition.json

artifacts:
  files: taskdefinition.json
